### ISSUE TITLE
Ghost Controller

### ISSUE THREAD

**Issue by Zodsmar** [worldmaking/mischmasch#14]
@grrrwaaa I am working on creating the ghost structure, I know we want to have basically a complete scene graph from it which will be an exact replica of what is being drawn including controllers. The issue I am having is by creating ghost controllers I need more then just positional data. I need everything from the matrix to touch controls. I need an exact copy essentially of the controllers themselves. Using .copy() brings FPS down to 19 which is not good. I am not sure how to go about creating a ghost controller, since it would be an exact duplicate. Should I maybe just have a reference to the normal controller? So ghost controller still modifies the normal controller but at least the structure is an exact match?

**Comment by grrrwaaa** [comment]
We need the ghost to have the same transform matrix (that part we need to
copy every frame), the rest an be just a reference. ghost
controller.userData.controller
