### ISSUE TITLE
scheduling eval session(s) 

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#19]
ideal dates:
- Last friday of August?
- First Friday of September?

Graham suggested running expert interviews

- [ ] one person from hardware MS community

- [ ] one person from VR

- [ ] one person used to visual programming

**Comment by Zodsmar** [comment]
These dates seem to work well for me. It gives us the time we need to get everything sorted out.

**Comment by michaelpalumbo** [comment]
changed to low priority until we get the stability milestone completed
