### ISSUE TITLE
are signals unipolar or bipolar in genish?

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#191]
we need to set ranges on signal inputs and certain knobs, in mischmaschOps.json -- so what kind of signals are we dealing with?

**Comment by grrrwaaa** [comment]
Signals in genish can have any value.

It's smart to encourage working in sensible ranges (0 to 1, -1 to 1, etc.) where possible, but there's no benefit to limiting all signals to such ranges.  

The biggest challenge is Hz. I mentioned before that if we can work with an octave-like scale this would be much better than Hz.

**Comment by michaelpalumbo** [comment]
> It's smart to encourage working in sensible ranges (0 to 1, -1 to 1, etc.) where possible, but there's no benefit to limiting all signals to such ranges.

Ok, so should the ranges in the ops be specified in any particular way?

> The biggest challenge is Hz. I mentioned before that if we can work with an octave-like scale this would be much better than Hz.

i fully agree. I'll make a ticket for this. Might be outside scope for nuit blanche but worth considering for the general public

**Comment by michaelpalumbo** [comment]
freq knobs will now have a range of -10v to +10v. Default value is 3, which equals 130.8Hz
