### ISSUE TITLE
idea for a game of life matrix switch

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#31]
would be fun to have a matrix sequencer where active mappings are determined by a game of life simulation

https://4mscompany.com/vcam.php

**Comment by grrrwaaa** [comment]
About a year ago I also suggested a Langton's Ant based sequencer; I think it would work very interestingly. 

[Langton's Ant docu vid](https://www.youtube.com/watch?v=w6XQQhCgq5c)   (music by Vasulkas!)

**Comment by michaelpalumbo** [comment]
archiving this for now. would be interesting to get to but not my priority
