### ISSUE TITLE
Jacks-as-LEDs

### ISSUE THREAD

**Issue by grrrwaaa** [worldmaking/mischmasch#33]
A few hardware modules have a nice feature of putting an LED behind an output jack. Example:
http://antumbra.eu/content/1-modules/1-rot8/rot8_bg.jpg

It seems like this is something we could do in MSVR -- any output jack can also be an LED (and vice versa -- any LED can act as an outjack, just like any knob can act as an injack).

**Comment by michaelpalumbo** [comment]
Absolutely! Antumbra uses this method in a few of their redesigns of mutable instruments modules too (see the Atom, in particular). 

See also LED patch cords: https://www.muffwiggler.com/forum/viewtopic.php?p=1539101

**Comment by michaelpalumbo** [comment]
the output viz buffer from max and into node is ready, just need to code the outlet visualizations in VR

**Comment by michaelpalumbo** [comment]
redundant, see issue #7
