### ISSUE TITLE
Use Github LFS

### ISSUE THREAD

**Issue by Zodsmar** [worldmaking/mischmasch#43]
https://git-lfs.github.com/

Should we start using github lfs? Maybe for the larger history files etc.

**Comment by michaelpalumbo** [comment]
create a new repo called msvrData, install the git lfs to this. then only write our session files to this.

**Comment by Zodsmar** [comment]
Spent a while looking into this and once we have the stable version going I will make the feature branch and see if I can integrate it. For now I think that we should focus solely on getting it stable.

**Comment by michaelpalumbo** [comment]
Thanks Alex. Can you say whether LFS installs to just one branch or across
the repo, or is it global to the system?
