### ISSUE TITLE
Path Name Discrepancy 

### ISSUE THREAD

**Issue by Zodsmar** [worldmaking/mischmasch#44]
The scene_noise.json or any scene file for that matter comes in as a delta and gets created on enact delta. So the path for example is noise_0. However, whenever we create a new module we are using a function called "gensym()" which increments a nodeid and sets the userposeid. So the path name is now noise_0_0. However the menu is getting created and has 120 modules so the first object I make in the scene is now granola_120_0. This doesn't fit with the graph and we have an issue with look ups and the way that max and the server are aware of each module. 

Somehow we need to either repath everything or have the server handle the path name creation directly and not js client side.

This is a discussion we need to have and probably relatively soon because this seems to be a big issue from both clientjs and clientmax.

(If I am missing anything michael please attach it)

**Comment by michaelpalumbo** [comment]
one note is that the max client uses the first number for varname instance numbers and for gen out indices

**Comment by michaelpalumbo** [comment]
@Zodsmar Graham and I chatted today: 

the objects in the menu shouldn't have names, they don't need names, and they shouldn't exist in the OT Graph (they exist in the scene graph)
- they shouldn't have OT-style path names (i.e. noise_12_0)
- gensym() shouldn't exist in the client
