### ISSUE TITLE
using the controllers as gestural devices

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#5]
make a gen module which is a control-signal generator for each Vive controller (controller data to individual gen outs)

- [x] gestural controller module
would need to determine whether the controller data should come in on the same channel as the OTs, or on a separate socket.

**Comment by Zodsmar** [comment]
Not entirely sure what you mean by "control-signal generator" if you could elaborate a little bit more I might have some more insights

**Comment by michaelpalumbo** [comment]
For sure. Its a module which receives the positional/acceleration/etc data from a vive controller, and outputs each individual Vive parameter as gen~ signals. i.e. qw, qx, qy, qz would each have their own gen~ outlet. Its a way for a player to perform their synth using hand gestures, for example, and create more complex control mappings. At present the most complex control scheme possible is two one-to-one mappings, where each controller can only control one knob/switch at a time. 

This feature could pave part of the way to issue #8: If we can create mappings between data sources and module parameters, then a simple graphic score editor/player would be a reasonable step further

Another implementation of a control-signal generator for MSVR would be as a setting in the browser which lets the player assign a specific controller parameter i.e. 'qx' of rotation, onto a particular knob of a given module.

**Comment by Zodsmar** [comment]
The server is receiving head position and quaternions. Same for both controllers. This data can be pulled into max and used. If anything else is required let me know.

**Comment by michaelpalumbo** [comment]
created gendsp abstractions for controller1 and controller2; current problems:

- msvr_world.js currently scripts the outlets to poke objects (this is unnecessary and could lead to problems)
- the params and setparams for each abstraction are not being added to [gen~ msvr_world]
- haven't tested whether the msvr_world.js is correctly passing controller data to these objects via their params and setparams. 
- the controller data arrives via a JSON called "user_pose". this also contains 'head' data, as well as 'id' indicating which user is running the headset/controller (aka the source of the data). msvr_world.js is not yet filtering the data according to the id, which means all users will control the gesture data simultanesously (resulting in data collision/interference). one possible solution to this is when the controller abstraction is instantiated in VR, it is linked to the id of the user who created it at the time (this could create issues when relaunching the scene... but we can deal with that later)

**Comment by Zodsmar** [comment]
I spoke with graham today about this issue and whenever a user is connected to the server a unique user ID is set. Whenever the module for controller gestures is created we should be able to just assign the id to it. Right now I don't believe that we are storing that id anywhere useful so we would need to add it so it is more useful but the barebones of the id's is there.

**Comment by Zodsmar** [comment]
Setup username login which stores the data inside the localstorage and sends the id to the server. This id is unique for each user (Unless usernames are the same) which gives the ability to determine which person created the gestural device and will be used to link it. We can also now potentially change who has control over gestural modules with a toggle of some kind and a list of active users. This opens the doors for multiple people in one space playing together with multiple devices in one space.

**Comment by michaelpalumbo** [comment]
this is nearly ready. archiving this issue as most of what is discussed here is no longer relevant
