### ISSUE TITLE
code keeps getting added to msvr_world.js upon recompile. 

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#52]
hi @grrrwaaa , the following code gets added to msvr_world.js when the max patch is running and i make changes to it:

```javascript
import { max } from "gl-matrix/src/gl-matrix/vec2";

```

its always on the 1st line and causes the [js] object to throw the following error:

```shell
js: msvr_world.js: Javascript TypeError: max.post is not a function, line 122
js: error calling function client [msvr_world.js]
```

**Comment by grrrwaaa** [comment]
The "import" line is being inserted by VS Code, which is trying to be clever. You can turn that off with a preference. 

Also, maybe 'max.post' should be 'Max.post' ?

**Comment by michaelpalumbo** [comment]
Thanks, and in my nodje4max code I've always used lowercase "max" for the max-api without issue. Would prefer to avoid having to change that unless you think it's conflicting with another lib?
On Feb 20, 2020, 2:15 PM -0500, Graham Wakefield <notifications@github.com>, wrote:
	The "import" line is being inserted by VS Code, which is trying to be clever. You can turn that off with a preference.
Also, maybe 'max.post' should be 'Max.post' ?

**Comment by michaelpalumbo** [comment]
resolved in vscode
