### ISSUE TITLE
new branching strategy

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#58]
see https://github.com/worldmaking/worldmaking.github.io/wiki/Git-Best-Practices

for how to.

**Comment by Zodsmar** [comment]
This is great! Thanks for this Michael. I spoke with Graham today and he was saying that once we get ghostOrphan stable we will merge that to the develop branch and not master yet. Once we have it stable we should work on usability. Make sure its completely usable before we go to master. But as soon as we hit stable we definitely should do feature branches and keep it organized!

**Comment by michaelpalumbo** [comment]
exactly. well put.
