### ISSUE TITLE
should partially connected cables be considered valid in the OT?

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#67]
changed to low priority now that Alex omitted partially connected cables in VRClient. Check in after stability about reintegration

**Comment by Zodsmar** [comment]
At some point yes aka dangling  cables, but for stability and getting the OT's playing nicely its easier to just omit partially connected cables. For now that is not possible.

**Comment by michaelpalumbo** [comment]
related to #66
