### ISSUE TITLE
maintain the graph of the scene in the max client

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#71]

**Comment by grrrwaaa** [comment]
I have been working on this in a constrained setting yesterday/this morning and have made quite a few observations/conclusions that might nudge a little how we do this. It's a bit complicated to fit into an issue tracker though.

**Comment by michaelpalumbo** [comment]
@grrrwaaa ah ok. I am just seeing this now. I've made some progress as well. the server now hosts the got.js file. This means alex is accessing it now too through the webGLClient.

**Comment by michaelpalumbo** [comment]
note to self @michaelpalumbo come back to this work on lines 109-111 in msvrAudioClient.js

**Comment by michaelpalumbo** [comment]
> have made quite a few observations/conclusions that might nudge a little how we do this. It's a bit complicated to fit into an issue tracker though.
@grrrwaaa can we go over this together soon?

**Comment by michaelpalumbo** [comment]
outdated. see mischmasch.js
