### ISSUE TITLE
got.js validation

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#82]
1. create a series of edits, store in got/testing/deltas.json
2. using /got/test.js, load got/testing/deltas.json

- Simulate what it would mean for e.g. two different users to edit a module at the same time, and verify that the result works out the same regardless which order the messages come in, and verify that the inversion of those would return to the same original state.

- One thing to watch out for is floating point accuracy. We should accept that 0.001 is roughly equal to 0.002 or 0.0005 etc., and not flag those as a merge fail. I.e. float values should have a certain tolerance to be accepted as the same value (I'd say, a tolerance of +/- 0.01% is sufficient.) Maybe create a js function  
```javascript 
floatApproximatelyEqual(x, y)
``` 
and use that to compare any parameters

key is to treat tolerance as a percentage-of-current-value, not a fixed resolution. So, the tolerance size is larger when using large numbers. That's why a +/- 0.001% for example would work.
You can take the ratio of abs(x-y) / abs(x) to work on percentages
```javascript
// e.g. 
return (Math.abs(x-y)/Math.abs(x)) < 0.0001;
```

**Comment by michaelpalumbo** [comment]
here are the two propchange deltas I'm working with (i left out the preceding newnode deltas below):

```json
[
    {"op":"propchange","path":"lfo_1.rate","name":"value","from":0.17,"to":34},
    {"op":"propchange","path":"lfo_1.rate","name":"value","from":0.17,"to":36}
]
```

**Comment by michaelpalumbo** [comment]
we can distinguish deltas that are "orthogonal" (i.e. no conflict), such as two deltas that modify different objects. those can be merged without issue
the other kind is conflicts where it is not possible to apply BOTH deltas and maintain a valid graph

**Comment by michaelpalumbo** [comment]
https://docs.google.com/document/d/1_XEhgtPTkTjHukz5VrqO6XAuFhLWwwWqnHtX22JVYVI/edit?usp=sharing

**Comment by michaelpalumbo** [comment]
see https://github.com/worldmaking/gotlib 

work-in-progress: 
https://docs.google.com/document/d/1_XEhgtPTkTjHukz5VrqO6XAuFhLWwwWqnHtX22JVYVI/edit
https://docs.google.com/document/d/11lVFfyQkjDB1Cjw8n4oNSULtXrhU2wCrlJoCvYaWkdA/edit

**Comment by grrrwaaa** [comment]
Didn't see it mentioned above but don't want to lose it: some special care may be needed for specific property types. In particular, 'approximately equal' is tricker for quaternions, as the same orientation can be represented by very different sets of numbers. The approximatelyEqual test will need to take into account property type to be robust.

**Comment by michaelpalumbo** [comment]
> Didn't see it mentioned above but don't want to lose it: some special care may be needed for specific property types. In particular, 'approximately equal' is tricker for quaternions, as the same orientation can be represented by very different sets of numbers. The approximatelyEqual test will need to take into account property type to be robust.

Certainly. I'll open this up again so we don't lose track of it!

**Comment by michaelpalumbo** [comment]
Approx equal is likely at fault for some merge conflicts ive encountered lately, also related to quaternion
